language: android

jdk: oraclejdk8

android:
  components:
    - tools
    - build-tools-25.0.2
    - platform-tools

    # The SDK version used to compile your project
    - android-24
    - android-25

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-24
    - android-platform-24
    - sys-img-x86-android-tv-24

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-x86-android-tv-24